num_clients: 3
num_rounds: 50
epochs_per_round: 1
batch_size: 16
label_noise: 0.1
client_splits:
  - [0.9, 0.1]
  - [0.1, 0.9]
  - [0.5, 0.5]
rank: 4
learning_rate: 0.01
momentum: 0.9
dataset_root: "./data"
device: "mps"
